### ISSUE TITLE
Bug when search radius = 0

### ISSUE THREAD

**Issue by sadowsky-o-phd** [brada/caltag#2]
In caltag.m, line 620, a search radius is computed to validate saddle points.
When, for some reason, the outcome is rad == 0, this leads to several subsequent faults.
1. validate_point in line 637 always returns false because it processes no points.
2. meshgrid in line 667 returns a single-point grid (0,0), and subsequently imadjust in line 681 crashes due to bad input.

As it seems, the caltag function was writted assuming rad > 0, and if this is not the case it doesn't work properly.

My fix was to add after line 620: rad = max(rad, 2);

**Comment by brada** [comment]
Fixed, thanks.
